### ISSUE TITLE
Dependency conflicts when using Unsloth finetuned models

### ISSUE THREAD

**Issue by Yingjia-Wan** [Yixiao-Song/VeriScore#2]
Hi! Thank you again for the amazing work.

I am trying to use veriscore on your provided finetuned models for [claim extraction](https://huggingface.co/SYX/mistral_based_claim_extractor) and [verification](https://huggingface.co/SYX/llama3_based_claim_verifier). However, after fulfilling install requirements listed on [Unsloth](https://github.com/unslothai/unsloth?tab=readme-ov-file#conda-installation), I failed to run veriscore due to version conflicts.

## Error:
```
(veriscore) yingjiawan@skcpu3:~/alisa/VeriScore$ python3 -m veriscore.veriscore \
>   --data_dir ./data \
>   --input_file data_sample.jsonl \
>   --model_name_extraction SYX/mistral_based_claim_extractor \
>   --model_name_verification SYX/llama3_based_claim_verifier \
>   --use_external_extraction_model \
>   --use_external_verification_model
Traceback (most recent call last):
  File "/home/yingjiawan/anaconda3/envs/veriscore/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yingjiawan/anaconda3/envs/veriscore/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yingjiawan/alisa/VeriScore/veriscore/veriscore.py", line 209, in <module>
    vs = VeriScorer(model_name_extraction=args.model_name_extraction,
  File "/home/yingjiawan/alisa/VeriScore/veriscore/veriscore.py", line 52, in __init__
    self.claim_extractor = ClaimExtractor(model_name_extraction, cache_dir=self.cache_dir,
  File "/home/yingjiawan/alisa/VeriScore/veriscore/claim_extractor.py", line 14, in __init__
    from unsloth import FastLanguageModel
  File "/home/yingjiawan/anaconda3/envs/veriscore/lib/python3.9/site-packages/unsloth/__init__.py", line 146, in <module>
    from .models import *
  File "/home/yingjiawan/anaconda3/envs/veriscore/lib/python3.9/site-packages/unsloth/models/__init__.py", line 15, in <module>
    from .loader  import FastLanguageModel
  File "/home/yingjiawan/anaconda3/envs/veriscore/lib/python3.9/site-packages/unsloth/models/loader.py", line 15, in <module>
    from .llama import FastLlamaModel, logger
  File "/home/yingjiawan/anaconda3/envs/veriscore/lib/python3.9/site-packages/unsloth/models/llama.py", line 18, in <module>
    from ._utils import *
  File "/home/yingjiawan/anaconda3/envs/veriscore/lib/python3.9/site-packages/unsloth/models/_utils.py", line 132, in <module>
    raise ImportError(
ImportError: Unsloth: Your xformers version of 0.0.27 is too new.
Please downgrade xformers via `pip install --force-reinstall "xformers<0.0.27"
```

## How to reproduce the error:
I completed the following setup in my conda env, based on the [Unsloth library you referenced](https://github.com/unslothai/unsloth). This conda env works well for running veriscore on API models like gpt4.
```
conda install pytorch pytorch-cuda=12.1 cudatoolkit -c pytorch -c nvidia
conda install xformers -c xformers
pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
pip install --no-deps "trl<0.9.0" peft accelerate bitsandbytes
```
Then I ran the following to run veriscore (which returned the error above):
```
python3 -m veriscore.veriscore \
  --data_dir ./data \
  --input_file data_sample.jsonl \
  --model_name_extraction SYX/mistral_based_claim_extractor \
  --model_name_verification SYX/llama3_based_claim_verifier \
  --use_external_extraction_model \
  --use_external_verification_model
```

## Failed Debugging attempts:
I tried `pip install --force-reinstall "xformers<0.0.27"` or `conda install` an earlier version. They didn't work.

## Question:
I would appreciate it so much if you could provide any help or suggestion regarding the issue. For example, can we know the exact requirement list for your fine-tuned models? Thank you in advance!

**Comment by Yingjia-Wan** [comment]
Update:

I loaded the finetuned models successfully by upgrading my python version from 3.9 to 3.10, and then installing Unsloth requirements all over again.

**Comment by mungg** [comment]
Glad to hear it got resolved!
